stages:
  - style-check
  - build
  - test

variables:
  FEDORA_IMG: registry.freedesktop.org/ruff/wocky/master:v1
  DEBIAN_IMG: registry.freedesktop.org/ruff/wocky/debtest:v1
  DEBSTB_IMG: registry.freedesktop.org/ruff/wocky/debstbl:v1
  SUSELP_IMG: registry.freedesktop.org/ruff/wocky/osuselp:v1
  SUSETW_IMG: registry.freedesktop.org/ruff/wocky/osusetw:v1
  WOCKY_DEBUG: all
  #G_MESSAGES_DEBUG: all

.default:
  before_script:
    - bash autogen.sh
  cache:
    key: "$CI_JOB_IMAGE:$CI_COMMIT_SHA"
    untracked: true

.defbuild:
  extends: .default
  stage: build
  script:
    - make

.deftest:
  extends: .default
  stage: test
  script:
    - make check
  artifacts:
    when: always
    paths:
      - "tests/test-old-report.xml"
      - "tests/test-new-report.xml"

style-check:
  image: $FEDORA_IMG
  extends: .default
  stage: style-check
  script:
    - make -C wocky check-local

fedora-x86_64-build:
  image: $FEDORA_IMG
  extends: .defbuild

fedora-x86_64-test:
  image: $FEDORA_IMG
  extends: .deftest

debian-x86_64-build:
  image: $DEBIAN_IMG
  extends: .defbuild

debian-x86_64-test:
  image: $DEBIAN_IMG
  extends: .deftest

opensuse-x86_64-build:
  image: $SUSETW_IMG
  extends: .defbuild

opensuse-x86_64-test:
  image: $SUSETW_IMG
  extends: .deftest

debian-stable-x86_64-build:
  image: $DEBSTB_IMG
  extends: .defbuild

debian-stable-x86_64-test:
  image: $DEBSTB_IMG
  extends: .deftest

opensuse-stable-x86_64-build:
  image: $SUSELP_IMG
  extends: .defbuild

opensuse-stable-x86_64-test:
  image: $SUSELP_IMG
  extends: .deftest
