name: Simple CI
on:
  push:
  pull_request:

jobs:
  build-meson:
    runs-on: ubuntu-20.04
    timeout-minutes: 10
    steps:
    - uses: actions/checkout@v2
    - name: Install prereqs
      run: |-
        sudo apt-get update && sudo apt-get install --no-install-recommends -qq -y build-essential \
        ccache meson libglib2.0-dev glib-networking telepathy-gabble libsasl2-dev libxml2-dev \
        libsoup2.4-dev libsasl2-modules-gssapi-mit libsqlite3-dev libssl-dev libgnutls28-dev \
        gnutls-bin gobject-introspection libgirepository1.0-dev gtk-doc-tools
    - name: Bootstrap
      run: meson _b -Dgoogle-relay=true -Dintrospection=enabled -Dgtk_doc=true -Dnonstandard-scram=true
    - name: Syntax
      run: ninja -C _b check
    - name: Build
      run: ninja -C _b
    - name: Run tests
      run: meson test -C _b
    - name: Build docs
      run: ninja -C _b wocky-doc
    - name: Artifacts
      uses: actions/upload-artifact@v2
      with:
        path: |
          _b/meson-logs/
          _b/docs/

  build-autotools:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
    - uses: actions/checkout@v2
    - name: Install prereqs
      run: |-
        sudo apt-get update && sudo apt-get install --no-install-recommends -qq -y build-essential \
        ccache automake libtool libglib2.0-dev glib-networking telepathy-gabble libsasl2-dev \
        libxml2-dev libsoup2.4-dev libsasl2-modules-gssapi-mit gnutls-bin libsqlite3-dev \
        libssl-dev libgnutls28-dev
    - name: Bootstrap
      run: bash autogen.sh
    - name: Code Syntax Check
      run: make -C wocky check-local
    - name: Test Syntax Check
      run: make -C tests check-coding-style
    - name: Build
      run: make
    - name: Run TLSv1.3 test
      run: make -C tests test-new
    - name: Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: Reports
        path: tests/test*report.xml
